<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Process\Exception\ExceptionInterface" namespace="Symfony\Component\Process\Exception" name="ExceptionInterface" abstract="false" final="false" start="19" end="21">
  <file path="//var/www/html/vendor/symfony/process/Exception" file="ExceptionInterface.php" realpath="/var/www/html/vendor/symfony/process/Exception/ExceptionInterface.php" size="450" time="2022-04-08T05:07:18+00:00" unixtime="1649394438" sha1="0e9fc700ce15378473a219d1b53db3819699696d" relative="ar/www/html/vendor/symfony/process/Exception/ExceptionInterface.php"/>
  <docblock>
    <description compact="Marker Interface for the Process Component."/>
    <author value="Johannes M. Schmitt &lt;schmittjoh@gmail.com&gt;"/>
  </docblock>
  <extends full="Throwable" namespace="" name="Throwable"/>
  <implementors>
    <class full="Symfony\Component\Process\Exception\ProcessSignaledException" namespace="Symfony\Component\Process\Exception" name="ProcessSignaledException"/>
    <class full="Symfony\Component\Process\Exception\ProcessFailedException" namespace="Symfony\Component\Process\Exception" name="ProcessFailedException"/>
    <class full="Symfony\Component\Process\Exception\ProcessTimedOutException" namespace="Symfony\Component\Process\Exception" name="ProcessTimedOutException"/>
    <class full="Symfony\Component\Process\Exception\InvalidArgumentException" namespace="Symfony\Component\Process\Exception" name="InvalidArgumentException"/>
    <class full="Symfony\Component\Process\Exception\RuntimeException" namespace="Symfony\Component\Process\Exception" name="RuntimeException"/>
    <class full="Symfony\Component\Process\Exception\LogicException" namespace="Symfony\Component\Process\Exception" name="LogicException"/>
  </implementors>
  <parent full="Throwable" namespace="" name="Throwable">
    <method name="getMessage" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the message"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getCode" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the exception code"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getFile" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the file in which the exception was created"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getLine" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the line on which the object was instantiated"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getTrace" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace"/>
      <return type="array"/>
    </docblock>
  </method>
    <method name="getTraceAsString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace as a string"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getPrevious" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Returns the previous Throwable"/>
      <return type="Throwable"/>
    </docblock>
  </method>
    <method name="__toString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets a string representation of the thrown object"/>
      <return type="string"/>
    </docblock>
  </method>
  </parent>
</interface>
