<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Console\Exception\ExceptionInterface" namespace="Symfony\Component\Console\Exception" name="ExceptionInterface" abstract="false" final="false" start="19" end="21">
  <file path="//var/www/html/vendor/symfony/console/Exception" file="ExceptionInterface.php" realpath="/var/www/html/vendor/symfony/console/Exception/ExceptionInterface.php" size="425" time="2022-04-12T16:02:29+00:00" unixtime="1649779349" sha1="40ad0549aa11597e4e60a7b92c4e623a824467c2" relative="ar/www/html/vendor/symfony/console/Exception/ExceptionInterface.php"/>
  <docblock>
    <description compact="ExceptionInterface."/>
    <author value="Jérôme Tamarelle &lt;jerome@tamarelle.net&gt;"/>
  </docblock>
  <extends full="Throwable" namespace="" name="Throwable"/>
  <implementors>
    <class full="Symfony\Component\Console\Exception\CommandNotFoundException" namespace="Symfony\Component\Console\Exception" name="CommandNotFoundException"/>
    <class full="Symfony\Component\Console\Exception\InvalidOptionException" namespace="Symfony\Component\Console\Exception" name="InvalidOptionException"/>
    <class full="Symfony\Component\Console\Exception\NamespaceNotFoundException" namespace="Symfony\Component\Console\Exception" name="NamespaceNotFoundException"/>
    <class full="Symfony\Component\Console\Exception\MissingInputException" namespace="Symfony\Component\Console\Exception" name="MissingInputException"/>
    <class full="Symfony\Component\Console\Exception\MissingInputException" namespace="Symfony\Component\Console\Exception" name="MissingInputException"/>
    <class full="Symfony\Component\Console\Exception\InvalidArgumentException" namespace="Symfony\Component\Console\Exception" name="InvalidArgumentException"/>
    <class full="Symfony\Component\Console\Exception\RuntimeException" namespace="Symfony\Component\Console\Exception" name="RuntimeException"/>
    <class full="Symfony\Component\Console\Exception\LogicException" namespace="Symfony\Component\Console\Exception" name="LogicException"/>
  </implementors>
  <parent full="Throwable" namespace="" name="Throwable">
    <method name="getMessage" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the message"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getCode" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the exception code"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getFile" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the file in which the exception was created"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getLine" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the line on which the object was instantiated"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getTrace" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace"/>
      <return type="array"/>
    </docblock>
  </method>
    <method name="getTraceAsString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace as a string"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getPrevious" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Returns the previous Throwable"/>
      <return type="Throwable"/>
    </docblock>
  </method>
    <method name="__toString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets a string representation of the thrown object"/>
      <return type="string"/>
    </docblock>
  </method>
  </parent>
</interface>
